spring.application.name=technology-service

# Configuracion de MySQL
spring.r2dbc.url=r2dbc:mysql://${TECHNOLOGY_MYSQL_HOST}:${TECHNOLOGY_MYSQL_PORT}/${TECHNOLOGY_MYSQL_DATABASE}
spring.r2dbc.username=${TECHNOLOGY_MYSQL_USERNAME}
spring.r2dbc.password=${TECHNOLOGY_MYSQL_PASSWORD}

# Ejecutar scripts de inicializacion
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Configuracion de Springdoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
